language: node_js
node_js:
- node
env:
  global:
  - secure: IPGdNVlukydAQHyyGfIUfs5RCedWGn87Bs82Ewt0uBC7I8ddrEZ1yp63VPLX6ViCQih409ymmerOtqGMHM+SOcGB1WkQSsBAWT21IfwoDtyyGa41cOpTGupBXZWOP1/6S1ZwG7jRJn3z/dR7t4t/poFvdzDUrIMPRjSUqXyYI45nOzUZxce18xznYuNeqCM13/SSSR43lHWpRqieMHEqV8LoIP2U3GGVFxRV+8OiMWN7egByQE3vp6QXTsay+RC1ORO8d1aTLYUU7q0UQyWvBcMLcD2hJcB4EUFDE5iOO5hyzYHlLSY7n6097mZJ2S97cgFu48uQrRDoETchS1WM69OupR5qLY/JabM95yDB0pq/v78x79ryIccqufVAVRk7X1GDVDBJc7UYcA9jPZCcEduGTI1+QxLDV+fOZqyfK/crkJeTw2A+JepFqDX+ZGcgOFLROiGF9CuOePUTjThWEbzlsvfPrilRzYi0nhsssI6iBYEHJXzk8Z/x3a9/Jbl3QrNAGRcMngINKYfndU6/EXMAlWDNzMxK8LzeQn+nv70etOned4WF3QkU8qF7uBJtShPAefqV7UzPJdnk7NQgssptfPjoAYItM126pITXOcVsVc2JJKoqn3AaHfa5v757WGC2TLMXBooX3xfsZhBH4pVhAF/lzleI7F9Fu50MA3w=
  - secure: aFncKHRXjYWzshkF9WvLRuLm/h5//l3paDX87vedtRNPjd5dkdyw+nkG31yRBi9Xy/270jQsLs1JMBzBby8aS/sPXq2wo/N3dQwtZjuQpRVVV+eKszulvkH735ZdGA7Yt+a6CIn4OA7TLs8IYmmbaWEOPSOKhFo3sTw/dcLd9trqjXwpUSQFtnRZBgY4nBaMwwOTSIQapvmwm9agkeTCTcTDY1ZG9Zo8AGBpcUV0EMX3JVPHMQpWE7OidrsM1057c9tmwvH3ZV0oaBtVlHEOZNdbVPFDWZYV2MbciBk31dgFv7g5Nl3CiBHCcIIj5OkzZW8Ea8PY3NvRbH7tLIPhdoYNhyL19Y/hPIPU66tzihsoFpACm5DVCwh2a07vNzhNzpecjvqomYcp36dZT8TeE+NyAGqGGrwoC1637HTYDHh3/RoA7EjLIv39hwI8B4oRdb/WJzJJ2Z6zMjucxDg6Z+/7wV+YJi3jYlmVoml3l811xgYSr6Ip3+XtNquh3Ov9ZUyN75dNoBuYAluVKqTeD4z3NgXAYaRJ2NC9Xdo3DGTcwpZjCJ5fGk4VNJaFV+nw3K2wmXLLDdlFdKJ2lRkLm9YPV/Q+vR0ohVUrihrrZVkD8IFjwgiL2Y38zBhwAkKrmiNbnDqaADqn6mGrTzkKSfeMxpc38f9Iz0z+mHuP4IA=
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- yarn lint
- yarn coverage
- yarn build
after_script:
- "./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT"
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/user-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean
  deploy --settings deploy/settings.xml && exit 0; fi
